name = 'theweb3-ninja'
main = "worker/index.ts"
compatibility_date = "2025-08-15"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]
account_id = "8207be57dc3a88f50bc29b302ef959ed"
workers_dev = true

kv_namespaces = [
  { binding = "KV_THEWEB3NINJA", id = "022d0818906e4f4e9b94c83620278eac" }
]

[assets]
directory = "./dist/client"
not_found_handling = "404-page"
html_handling = "force-trailing-slash"
binding = "ASSETS"

[vars]
CF_ACCOUNT_ID = "8207be57dc3a88f50bc29b302ef959ed"
ZONE_ID = "7a38e3c80fdc306f010604a09801d180"
EMAIL_LIST_ID_ENV = "4ae43d72-d43d-11ef-8467-6f7dbc1a852e"
VITE_ENV = "development"

[observability]
logs.enabled = true

[env.staging]
name = "theweb3-ninja"
workers_dev = true
routes = [
    { pattern = "*staging-theweb3-ninja.ness0.workers.dev/*", zone_name = "ness0.workers.dev" },
]
kv_namespaces = [
  { binding = "KV_THEWEB3NINJA", id = "022d0818906e4f4e9b94c83620278eac" }
]

[env.staging.vars]
CF_ACCOUNT_ID = "8207be57dc3a88f50bc29b302ef959ed"
ZONE_ID = "7a38e3c80fdc306f010604a09801d180"
EMAIL_LIST_ID_ENV = "4ae43d72-d43d-11ef-8467-6f7dbc1a852e"
VITE_ENV = "staging"

[env.staging.observability]
logs.enabled = true

[env.production]
name = "theweb3-ninja"
routes = [
    { pattern = "theweb3.ninja/*", zone_name = "theweb3.ninja" },
]
kv_namespaces = [
  { binding = "KV_THEWEB3NINJA", id = "022d0818906e4f4e9b94c83620278eac" }
]

[env.production.vars]
CF_ACCOUNT_ID = "8207be57dc3a88f50bc29b302ef959ed"
ZONE_ID = "7a38e3c80fdc306f010604a09801d180"
EMAIL_LIST_ID_ENV = "4ae43d72-d43d-11ef-8467-6f7dbc1a852e"
VITE_ENV = "production"

[env.production.observability]
logs.enabled = true
